@echo off
set tempcarname=AstonMartin_VulcanRewardRecycled_2016_White

echo     { >"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "unid": 2453, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "crdb": "AstonMartin_VulcanRewardRecycled_2016", >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "awar": false, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "grsp": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         4.17, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         2.34, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         1.52, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         1.14, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         0.87, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         0.69 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       ], >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "fidr": 2.0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "nlpr": 1.0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "tafr": 0.5, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "titp": 0.5, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "trld": 0.0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "tssp": 0.5, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "tssr": 0.5, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "ttup": 0.5, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "ttpp": 0.52, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "appi": 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "orpi": 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "apiid": 709, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "oriid": 709, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "apcid": 17, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "orcid": 17, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "aplid": 271, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "orlid": 271, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "aplzsid": 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "orlzsid": 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "apln": "", >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "apcn": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         "AstonMartin_VulcanRewardRecycled_2016_Wheel1A_3D" >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       ], >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "bqmt": 0.0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "bhmt": 0.0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "ditr": 0.0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "rcat": 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "rwon": 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "msou": 5909996, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "nuub": 35, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "ccna": 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "upst": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "lvlo": 6, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "lvlf": 6, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "lvls": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             } >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "lvlo": 6, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "lvlf": 6, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "lvls": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             } >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "lvlo": 6, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "lvlf": 6, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "lvls": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             } >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "lvlo": 6, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "lvlf": 6, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "lvls": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             } >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "lvlo": 6, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "lvlf": 6, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "lvls": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             } >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "lvlo": 6, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "lvlf": 6, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "lvls": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             } >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "lvlo": 6, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "lvlf": 6, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "lvls": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "ulpf": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               "fsg": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 2, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo                 3 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo               ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo             } >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           ] >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         } >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       ], >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "rpst": [ >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "rvlo": 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "rvlf": 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "rvlo": 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "rvlf": 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "rvlo": 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "rvlf": 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "rvlo": 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo           "rvlf": 0 >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         } >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       ], >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "grpsp": 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "grpts": 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "cppi": 714, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "cepi": 2104, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "tdut": 11.858, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "tdtt": 7.649, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "ttqm": 5.399, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "tthm": 7.649, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "tt60": 1.0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "tt1h": 1.706, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "ctie": "TIER_5", >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "csrc": "Gacha", >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "nupl": { >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         "txt": "", >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo         "cpf": false >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "esup": true, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "elcl": 0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "gacp": false, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "paid": 859, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "wpid": 2147483647, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "inid": 709, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "caid": 17, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "lzsid": 1, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "livid": 271, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "whbn": "Wheel1A_3D", >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "tlad": 0.0, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo       "need": false >>"%USERPROFILE%\Documents\CSRPpro\Temp"
echo     }, >>"%USERPROFILE%\Documents\CSRPpro\Temp"
move "%USERPROFILE%\Documents\CSRPpro\Temp" "%USERPROFILE%\Documents\CSRPpro\TempFiles\%tempcarname%" >nul
START "%cartempname%" Notepad++.exe "%USERPROFILE%\Documents\CSRPpro\TempFiles\%tempcarname%"